/**
 * generated by Xtext
 */
package no.pdigre.validation;

import no.pdigre.validation.AbstractPSQTValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PSQTValidator extends AbstractPSQTValidator {
}
