/*
 * generated by Xtext
 */
package no.pdigre;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PSQTRuntimeModule extends no.pdigre.AbstractPSQTRuntimeModule {

}
