/*
 * generated by Xtext
 */
package no.pdigre.ui.contentassist

import no.pdigre.ui.contentassist.AbstractPSQTProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PSQTProposalProvider extends AbstractPSQTProposalProvider {
}
