/*
 * generated by Xtext
 */
package no.pdigre.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import no.pdigre.ui.internal.PSQTActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PSQTExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PSQTActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PSQTActivator.getInstance().getInjector(PSQTActivator.NO_PDIGRE_PSQT);
	}
	
}
