/*
* generated by Xtext
*/
package no.pdigre;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PSQTUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return no.pdigre.ui.internal.PSQTActivator.getInstance().getInjector("no.pdigre.PSQT");
	}
	
}
